version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/synced
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=somerandomsecret
      - OPENAI_BASE_URL=https://api.groq.com/openai/v1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=llama-3.3-70b-versatile
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 