create extension if not exists pgcrypto with schema public;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.learning_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id text,
  session_handle text,
  topic text,
  status text not null default 'active' check (status in ('active','ended','error','disconnected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  ended_at timestamptz
);

create index if not exists learning_sessions_user_id_idx on public.learning_sessions (user_id, created_at desc);

alter table public.learning_sessions enable row level security;

create policy "learning_sessions_select_own"
  on public.learning_sessions for select
  to authenticated
  using (auth.uid()::uuid = user_id);

create policy "learning_sessions_insert_own"
  on public.learning_sessions for insert
  to authenticated
  with check (auth.uid()::uuid = user_id);

create policy "learning_sessions_update_own"
  on public.learning_sessions for update
  to authenticated
  using (auth.uid()::uuid = user_id)
  with check (auth.uid()::uuid = user_id);

create policy "learning_sessions_delete_own"
  on public.learning_sessions for delete
  to authenticated
  using (auth.uid()::uuid = user_id);

drop trigger if exists set_updated_at on public.learning_sessions;
create trigger set_updated_at
before update on public.learning_sessions
for each row execute function public.set_updated_at();

create table if not exists public.learning_visualizations (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.learning_sessions(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  library text not null check (library in ('react','p5','three')),
  explanation text not null,
  code text not null,
  panel_dimensions jsonb,
  sequence integer generated by default as identity,
  data jsonb
);

create index if not exists learning_visualizations_session_id_idx on public.learning_visualizations (session_id, created_at);

alter table public.learning_visualizations enable row level security;

create policy "learning_visualizations_select_own"
  on public.learning_visualizations for select
  to authenticated
  using (
    exists (
      select 1
      from public.learning_sessions s
      where s.id = public.learning_visualizations.session_id and s.user_id = (select auth.uid())::uuid
    )
  );

create policy "learning_visualizations_insert_own"
  on public.learning_visualizations for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.learning_sessions s
      where s.id = public.learning_visualizations.session_id and s.user_id = (select auth.uid())::uuid
    )
  );

create policy "learning_visualizations_update_own"
  on public.learning_visualizations for update
  to authenticated
  using (
    exists (
      select 1
      from public.learning_sessions s
      where s.id = public.learning_visualizations.session_id and s.user_id = (select auth.uid())::uuid
    )
  )
  with check (
    exists (
      select 1
      from public.learning_sessions s
      where s.id = public.learning_visualizations.session_id and s.user_id = (select auth.uid())::uuid
    )
  );

create policy "learning_visualizations_delete_own"
  on public.learning_visualizations for delete
  to authenticated
  using (
    exists (
      select 1
      from public.learning_sessions s
      where s.id = public.learning_visualizations.session_id and s.user_id = (select auth.uid())::uuid
    )
  );

drop trigger if exists set_updated_at on public.learning_visualizations;
create trigger set_updated_at
before update on public.learning_visualizations
for each row execute function public.set_updated_at();


